'use client';

import TypeIt from 'typeit-react';

const TypewriterText = () => {
  return (
    <TypeIt
      options={{
        speed: 200,
        startDelay: 1600,
        loopDelay: 1200,
        deleteSpeed: 100,
      }}
      getBeforeInit={(instance) => {
        instance
          .type('Web Developer', { delay: 100 })
          .pause(1500)
          .move(-9, { speed: 200 })
          .delete(9)
          .pause(1500)
          .type('Frontend ', { delay: 100 })
          .pause(1000)
          .move(10, { speed: 200 })
          .type(' (React.js)', { delay: 100 })
          .pause(1779)
          .delete(30)
          .pause(480)
          .type('P')
          .pause(332)
          .type('r')
          .pause(84)
          .type('o')
          .pause(452)
          .type('b')
          .pause(333)
          .type('l')
          .pause(65)
          .type('e')
          .pause(231)
          .type('m')
          .pause(271)
          .type(' ')
          .pause(878)
          .type('S')
          .pause(325)
          .type('o')
          .pause(192)
          .type('l')
          .pause(103)
          .type('v')
          .pause(130)
          .type('e')
          .pause(168)
          .type('r')
          .pause(1223)
          .delete(20)
          .pause(482)
          .type('T')
          .pause(205)
          .type('e')
          .pause(311)
          .type('c')
          .pause(117)
          .type('h')
          .pause(495)
          .type(' ')
          .pause(294)
          .type('E')
          .pause(266)
          .type('n')
          .pause(539)
          .type('t')
          .pause(159)
          .type('h')
          .pause(236)
          .type('u')
          .pause(60)
          .type('s')
          .pause(136)
          .type('i')
          .pause(122)
          .type('a')
          .pause(167)
          .type('s')
          .pause(632)
          .type('t')
          .pause(1862)
          .type('!')
          .pause(1215)
          .delete(20)
          .pause(1779)
          .type('E')
          .pause(380)
          .type('n')
          .pause(111)
          .type('g')
          .pause(138)
          .type('i')
          .pause(163)
          .type('n')
          .pause(203)
          .type('e')
          .pause(245)
          .type('e')
          .pause(275)
          .type('r')
          .move(-8, { speed: 308 })
          .type('F')
          .pause(220)
          .type('r')
          .pause(81)
          .type('o')
          .pause(107)
          .type('n')
          .pause(117)
          .type('t')
          .pause(213)
          .type('e')
          .pause(149)
          .type('n')
          .pause(93)
          .type('d')
          .pause(118)
          .type(' ')
          .move(12)
          .go();

        return instance;
      }}
    />
  );
};

export default TypewriterText;
